name: 🚀 Feature Request
description: Suggest an idea, feature or enhancement.
labels: ["Type: Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request. It helps make the project better.
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve this problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
